name: dashboard
description: A new Flutter project.
 
 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0" 
dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_database: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  get: ^4.6.5
  ionicons: ^0.2.1
  flutter_otp_text_field: ^1.0.1
  cloud_firestore: ^3.4.2
  cached_network_image: ^3.2.1 
   
flutter:
 
  uses-material-design: true
  assets:
    - assets/images/
 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700 
 